spring.datasource.url=${db.url}
spring.datasource.username=${db.user}
spring.datasource.password=${db.password}
spring.datasource.driver-class-name=${db.driver}

db.url=jdbc:mysql://mysql-3c043562-gustavo-4c3e.j.aivencloud.com:25606/FrangosInfinity?ssl-mode=REQUIRED
db.user=avnadmin
db.password=AVNS_cOO-TLZs69Y5yOqnATW
db.driver=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties..hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.jdbc.lob.non_contextual_creation=true

spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.connection-test-query=SELECT 1
spring.datasource.hikari.validation-timeout=5000
spring.datasource.hikari.max-lifetime=120000
spring.datasource.hikari.keepalive-time=30000