

app.name=Frangos Infinity
app.version=1.0.0
app.baseUrl=http://localhost:8082

db.url=jdbc:mysql://mysql-39b41c15-estudante-063d.j.aivencloud.com:17600/FrangosInfinity?sslMode=REQUIRED
db.user=avnadmin
db.password=AVNS_3yWAYkaPbT8UwyqWfgu
db.driver=com.mysql.cj.jdbc.Driver

iot.ip.base=192.168.1
iot.porta.base=9000
iot.tempo.timeout=5000

qr.code.diretorio=./qrcodes/
qr.code.tamanho=300
qr.code.tempo.expiracao=120

mesa.capacidade.maxima=20
mesa.numero.maximo=999

geo.latitude.base=-23.550520
geo.longitude.base=-46.633308
geo.variacao.maxima=0.01

email.user=frangosfritosoficial@gmail.com
email.password=prtyurvwytybynja