app.name=Frangos Infinity
app.version=1.0.0
app.baseUrl=http://localhost:8082
app.description=Sistema de gestão da Lanchonete Frango's Fritos

server.port=8082
server.error.include-message=always
server.error.include-binding-errors=always