spring.config.import=classpath:application-app.properties,\
  classpath:application-database.properties,\
  classpath:application-iot.properties,\
  classpath:application-qrcode.properties,\
  classpath:application-mesa.properties,\
  classpath:application-geo.properties,\
  classpath:application-email.properties